#!/usr/bin/env python3
"""Candidate question generation for the ABAP vault.

GraphRAG generates follow-up questions with an LLM because its graph is
auto-extracted and has no schema to reason over. This vault has the opposite
property: a fixed ontology of 21 page types, mandatory frontmatter, and
mandatory link patterns. That means the most valuable questions — the ones a
handover reader will hit — are *derivable* from structure, with no model call
and no nondeterminism.

Each rule below cites the clause in CLAUDE.md it enforces. Everything it emits
is a question for a human to answer or discard, never an assertion.

Usage:
    python3 .github/scripts/question-gen.py                 # report to stdout
    python3 .github/scripts/question-gen.py --out FILE      # also write report
    python3 .github/scripts/question-gen.py --write         # update Open-Questions pages

--write inserts a fenced AUTO block into an existing `Open-Questions/{WS}.md`
and replaces it on later runs. It never edits a byte outside its own markers,
and it never creates a page: a workstream with no open-questions page is
reported as a finding, because creating pages is the ingest pipeline's job.
"""

import argparse
import collections
import datetime
import os
import re
import sys

from vault_model import Vault, WIKILINK_RE

AUTO_BEGIN = "<!-- AUTO:questions BEGIN — generated by question-gen.py, do not hand-edit -->"
AUTO_END = "<!-- AUTO:questions END -->"

# A wikilink target containing " - " follows a vault naming pattern, so an
# unresolved one is a promised page. Targets like ZINSURANCE, BUT000 or
# BAPI_TRANSACTION_COMMIT are SAP objects and belong in a Dependencies list,
# not in the vault as pages of their own.
VAULT_NAME_HINT = " - "

SKIP_STATUSES = {"archived"}


class Finding:
    __slots__ = ("rule", "workstream", "question", "why", "sources")

    def __init__(self, rule, workstream, question, why, sources):
        self.rule = rule
        self.workstream = workstream or ""
        self.question = question
        self.why = why
        self.sources = sources

    def sort_key(self):
        return (self.workstream, self.rule, self.question)


# --------------------------------------------------------------------------
# Rules
# --------------------------------------------------------------------------

def related_paths(v, page):
    """Every page related to this one, in either direction.

    Direction is deliberately ignored. The question these rules ask is "can a
    teammate find X from here?", and the vault stores links bidirectionally —
    a relation recorded only as a backlink still answers the question.
    """
    return v.forward_edges[page.path] | v.inbound[page.path]


def linked_types(v, page):
    return {v.by_path[p].type for p in related_paths(v, page)}


def rule_dev_without_spec(v):
    for p in v.of_type("development"):
        if p.status in SKIP_STATUSES:
            continue
        if "spec" not in linked_types(v, p):
            yield Finding(
                "dev-no-spec", p.workstream,
                f"What is the functional/technical spec for **{p.name}**?",
                "Development record with no linked spec — Handover Criterion "
                "requires a spec for every custom object.",
                [p.path])


def rule_spec_without_dev(v):
    for p in v.of_type("spec"):
        if p.status in SKIP_STATUSES:
            continue
        if "development" not in linked_types(v, p):
            yield Finding(
                "spec-no-dev", p.workstream,
                f"Which development object implements **{p.name}**?",
                "Spec with no linked development record — either the object is "
                "unbuilt or its record is missing.",
                [p.path])


def rule_promised_pages(v):
    for target, sources in sorted(v.unresolved.items()):
        if VAULT_NAME_HINT not in target:
            continue  # SAP object, not a promised vault page
        ws = ""
        for s in sources:
            if v.by_path[s].workstream:
                ws = v.by_path[s].workstream
                break
        refs = ", ".join(f"[[{v.by_path[s].name}]]" for s in sorted(sources))
        yield Finding(
            "promised-page", ws,
            f"**{target}** is referenced by {len(sources)} page(s) but has no "
            f"record — is it in scope, and who owns it?",
            f"Unresolved wikilink from {refs}.",
            sorted(sources))


def rule_ai_generated_unvalidated(v):
    for p in v.pages:
        if p.status in SKIP_STATUSES:
            continue
        if "ai-generated" in p.tags:
            updated = p.front.get("updated", "unknown")
            yield Finding(
                "ai-unvalidated", p.workstream,
                f"Who is the SME validating **{p.name}**?",
                f"Tagged `ai-generated` (reconstructed from source, not confirmed "
                f"by a human), status `{p.status or '?'}`, last updated {updated}. "
                "Team rule: every ai-generated page gets SME review.",
                [p.path])


def rule_open_conflicts(v):
    for p in v.pages:
        if p.has_conflict:
            yield Finding(
                "open-conflict", p.workstream,
                f"Which claim stands in **{p.name}**? The conflict needs a Decision page.",
                "Page carries an unresolved `> [!warning] CONFLICT` block. Per the "
                "Conflict Check, only a human decision clears it.",
                [p.path])


def rule_missing_open_questions_page(v):
    have = {p.name for p in v.pages if p.in_zone("02-workstreams/Open-Questions/")}
    for slug in v.slugs_in_use():
        if slug not in have:
            yield Finding(
                "no-open-questions-page", slug,
                f"What is outstanding for **{slug}**? It has no rolling "
                f"open-questions page.",
                "Handover Criterion requires a current open-questions page with "
                "owners for every workstream.",
                [])


def _table_rows(body):
    """Yield (headers, cells) for every data row of every markdown table."""
    headers = None
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped.startswith("|"):
            headers = None
            continue
        cells = [c.strip() for c in stripped.strip("|").split("|")]
        if all(set(c) <= set("-: ") for c in cells if c):
            continue  # separator row
        if headers is None:
            headers = [c.lower() for c in cells]
            continue
        yield headers, cells


def rule_unowned_questions(v):
    for p in v.of_type("open-questions"):
        for headers, cells in _table_rows(p.body):
            if "question" not in headers or "owner" not in headers:
                continue
            q_i, o_i = headers.index("question"), headers.index("owner")
            if q_i >= len(cells) or o_i >= len(cells):
                continue
            question, owner = cells[q_i], cells[o_i]
            if not question or question in {"…", "..."}:
                continue  # empty template row
            if owner and owner not in {"—", "-", "TBD", "Unassigned", "…"}:
                continue
            yield Finding(
                "unowned-question", p.workstream,
                f"Who owns: _{question}_",
                f"Open question in **{p.name}** with no owner. Every open "
                "question needs a named owner.",
                [p.path])


def rule_estimate_without_actual(v):
    for p in v.of_type("development"):
        if p.status in SKIP_STATUSES:
            continue
        low = p.body.lower()
        if "estimate" in low and "actual" not in low:
            yield Finding(
                "estimate-no-actual", p.workstream,
                f"Has the actual effort for **{p.name}** been recorded yet?",
                "Development records an estimate but no actual. Team rule: "
                "estimates without actuals never become an estimation baseline. "
                "Fires for in-flight work too — the status vocabulary has no "
                "`complete` value, so completion cannot be detected.",
                [p.path])


def rule_no_standard_link(v):
    for p in v.of_type("development", "spec"):
        if p.status in SKIP_STATUSES:
            continue
        if not any(v.by_path[r].in_zone("01-standards") for r in related_paths(v, p)):
            yield Finding(
                "no-standard-link", p.workstream,
                f"Which coding or architecture standards does **{p.name}** follow?",
                "Mandatory Link Pattern: developments and specs link to the "
                "standards they follow (Zone 02 → Zone 01).",
                [p.path])


def rule_no_workstream_link(v):
    ws_pages = {p.name: p.path for p in v.pages
                if p.in_zone("02-workstreams/Workstreams/")}
    for p in v.pages:
        if not p.in_zone("02-workstreams/") or p.in_zone("02-workstreams/Workstreams/"):
            continue
        if p.status in SKIP_STATUSES:
            continue
        target = ws_pages.get(p.workstream)
        if target and target not in v.forward_edges[p.path]:
            yield Finding(
                "no-workstream-link", p.workstream,
                f"Which workstream owns **{p.name}**? It does not link to "
                f"[[{p.workstream}]].",
                "Mandatory Link Pattern: everything in Zone 02 links to its "
                "workstream page.",
                [p.path])


RULES = (
    rule_dev_without_spec,
    rule_spec_without_dev,
    rule_promised_pages,
    rule_ai_generated_unvalidated,
    rule_open_conflicts,
    rule_missing_open_questions_page,
    rule_unowned_questions,
    rule_estimate_without_actual,
    rule_no_standard_link,
    rule_no_workstream_link,
)


def generate(v):
    findings = []
    for rule in RULES:
        findings.extend(rule(v))
    return sorted(findings, key=lambda f: f.sort_key())


# --------------------------------------------------------------------------
# Output
# --------------------------------------------------------------------------

def build_report(findings, v):
    by_ws = collections.defaultdict(list)
    for f in findings:
        by_ws[f.workstream].append(f)

    out = []
    w = out.append
    w("# Candidate questions")
    w("")
    w(f"Derived from vault structure — {len(findings)} candidate(s) across "
      f"{len(by_ws)} group(s). Each is a question for a human to answer or "
      "discard, not an assertion.")
    w("")

    for ws in sorted(by_ws, key=lambda s: (s == "", s)):
        label = ws if ws else "No workstream (zones 01/03/04)"
        w(f"## {label}")
        w("")
        for f in by_ws[ws]:
            w(f"- {f.question}")
            w(f"    - _{f.why}_ `[{f.rule}]`")
        w("")

    counts = collections.Counter(f.rule for f in findings)
    w("## By rule")
    w("")
    for rule, n in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])):
        w(f"- `{rule}` — {n}")
    w("")
    return "\n".join(out)


def _no_wikilinks(text):
    """Strip [[wikilinks]] from generated text, rendering them as code spans.

    The AUTO block is inserted above `## Linked from`, so a wikilink inside it
    would be a genuine forward edge — and graph-health.py would then correctly
    demand a matching `## Linked from` entry on the target, failing --strict on
    links no human wrote. Generated scaffolding must never create graph edges.
    """
    return WIKILINK_RE.sub(lambda m: f"`{m.group(1).strip()}`", text)


def render_auto_block(findings, today):
    lines = [
        AUTO_BEGIN,
        "",
        "## Generated candidate questions",
        "",
        f"_Derived from vault structure on {today} by `question-gen.py`. Not "
        "curated: promote a question into the table above with a named owner, "
        "or delete it. This block is regenerated on every run._",
        "",
    ]
    for f in findings:
        lines.append(_no_wikilinks(f"- {f.question}"))
        lines.append(_no_wikilinks(f"    - _{f.why}_ `[{f.rule}]`"))
    lines.append("")
    lines.append(AUTO_END)
    return "\n".join(lines)


def write_blocks(v, findings, today, root):
    """Insert/replace the AUTO block in each existing Open-Questions/{WS}.md.
    Returns (updated_paths, skipped_workstreams)."""
    by_ws = collections.defaultdict(list)
    for f in findings:
        if f.workstream:
            by_ws[f.workstream].append(f)

    oq_pages = {p.name: p for p in v.pages
                if p.in_zone("02-workstreams/Open-Questions/")}

    updated, skipped = [], []
    for ws in sorted(by_ws):
        page = oq_pages.get(ws)
        if page is None:
            skipped.append(ws)
            continue

        block = render_auto_block(by_ws[ws], today)
        text = page.raw

        if AUTO_BEGIN in text and AUTO_END in text:
            new_text = re.sub(
                re.escape(AUTO_BEGIN) + r".*?" + re.escape(AUTO_END),
                lambda _m: block, text, flags=re.DOTALL)
        else:
            # place before "## Linked from" so backlinks stay the last section
            idx = text.find("\n## Linked from")
            insert = "\n" + block + "\n"
            new_text = (text[:idx] + "\n" + insert + text[idx:]) if idx != -1 \
                else text.rstrip("\n") + "\n" + insert

        if new_text != text:
            with open(os.path.join(root, page.path), "w", encoding="utf-8") as fh:
                fh.write(new_text)
            updated.append(page.path)

    return updated, skipped


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=".", help="vault root (default: cwd)")
    ap.add_argument("--out", help="also write the report to this file")
    ap.add_argument("--write", action="store_true",
                    help="insert/replace the AUTO block in existing Open-Questions pages")
    ap.add_argument("--date", default=datetime.date.today().isoformat(),
                    help="date stamp for the generated block (default: today)")
    args = ap.parse_args()

    v = Vault(args.root)
    findings = generate(v)
    report = build_report(findings, v)
    print(report)

    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(report + "\n")

    if args.write:
        updated, skipped = write_blocks(v, findings, args.date, args.root)
        print("## Written")
        print("")
        for path in updated:
            print(f"- updated `{path}`")
        for ws in skipped:
            print(f"- **skipped {ws}** — no `Open-Questions/{ws}.md`; "
                  "the ingest pipeline creates pages, this script does not")
        if not updated and not skipped:
            print("- nothing to write")

    return 0


if __name__ == "__main__":
    sys.exit(main())
